# TASK level variables
- name: variable from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Sivakumar"
    Duration: "110Hrs"
  tasks:
  - name: check varibales
    vars: #task level
      Course: "DevOps with AWS"
    ansible.builtin.debug:
      msg: "Hi, I am learnig {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"