- name: variables from PLAY level
  hosts: localhost
  tasks:
  - name: check varibales
    ansible.builtin.debug:
      msg: "Hi, I am learnig {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"